source: ./src
destination: ./dist
exclude: ['external', 'scss', '*.js', '*.css', '*.patch']
include: ['*.min.css', 'modernizr.js', '*.min.js']

name: 'strann.ca'
title: 'Stuart Trann'
description: 'a Front End Developer from Vancouver, BC'
markdown: redcarpet
paginate: 1
highlighter: true
# permalink: /:year-:month-:day/:title
permalink: /:categories/:title

author:
  twitter: https://twitter.com/estwo
  github: https://github.com/strann
  flickr: http://flickr.com/estwo
  rdio: http://rdio.com/chillmurray

github:
  repo: https://github.com/strann/strann.ca
