source: ./src
destination: ./dist
exclude: ['external', 'scss', 'js', '*.css']
include: ['*.min.css', '*.min.js']

title: 'Stuart Trann, a Front End Developer from Vancouver, BC'
markdown: redcarpet
paginate: 1
pygments: true
# permalink: /:year-:month-:day/:title
permalink: /:categories/:title

author:
  name: 'Stuart Trann'
  twitter: https://twitter.com/estwo
  github: https://github.com/strann

github:
  repo: https://github.com/strann/strann.ca
